### ISSUE TITLE
is the project in active development?

### ISSUE THREAD

**Issue by hbakhtiyor** [journeyapps/mongo-oplog-backup#4]
hi there,

i also found https://github.com/EqualExperts/Tayra project too, but unfortunately not in active development and supports only old version of mongodb.

but what's about your project?

cheers!

**Comment by rkistner** [comment]
As stated in the readme, this project is not currently production ready. If you do want to use it, make sure you familiarise yourself with the details of how the oplog and this tool works. We will not take responsibility for any data loss.

That said, we are using it in production ourselves, and haven't run into any major issues yet. We are not actively developing on the project, mostly because it is fine in the current state for our needs. We do add support for new MongoDB versions as we upgrade, but these are usually small changes.

There are some performance issues that we are aware of currently:

1. The `mongo-oplog-backup merge` command is fairly slow when working with large backups. Should be solvable by using something other than Ruby to do the merge.

2. If your oplog size is large (e.g. 50GB), the backup becomes slow, since MongoDB has to scan through the entire collection to find the last position for some reason. This can be solved by oplog tailing instead of running a cron job like we do.

**Comment by hbakhtiyor** [comment]
thanks for your comment

btw, what's your storing backups? if Amazon S3, which tools do you use for for that?

**Comment by rkistner** [comment]
It's designed to be used with S3 (separate files that can be uploaded individually), but we're not using S3 yet. Currently we're just storing it directly on EBS volumes (more expensive, but easier to setup).

**Comment by hbakhtiyor** [comment]
don't see any options of the tool for uploading to S3, doesn't have the feature out of the box
